if(CMAKE_VERSION VERSION_GREATER 2.6.2)
    message(STATUS "Detecting PkgConfig")
    find_package(PkgConfig REQUIRED)
    if(PKG_CONFIG_FOUND)
        message(STATUS "Detected PkgConfig ${PKG_CONFIG_EXECUTABLE}")
    else()
        message(FATAL_ERROR "Cmake failed to find pkg-config. Please check your pkg-config installation and ensure it works well.")
    endif()
else()
    include(cmake/xsetpic.findpkgconfig.tool.private.cmake)
    message(STATUS "Detecting PkgConfig")
    find_package(PkgConfig REQUIRED)
    if(PKG_CONFIG_FOUND)
        message(STATUS "Detected PkgConfig ${PKG_CONFIG_EXECUTABLE}")
    else()
        message(FATAL_ERROR "Cmake failed to find pkg-config. Please check your pkg-config installation and ensure it works well.")
    endif()
endif()
